delete?:
  responses:
    200:
      body:
        application/json:
          schema: types.OkStatus | string
          example: !include ../examples/ok-status-example.json
  securedBy:
    - oauth_2_0:
        scopes: [<<scope>>]
post?:
  responses:
    200:
      body:
        application/json:
          type: types.OkStatus | string
          example: !include ../examples/ok-status-example.json
  securedBy:
    - oauth_2_0:
        scopes: [<<scope>>]
securedBy:
  - oauth_2_0:
      scopes: [<<scope>>]
      #clientId: []
type: base
