#%RAML 1.0 Library

uses:
  c:  common.raml

types:

  ###############
  # User:
  ###############

  User-base:
    properties:
      firstname:
        required: true
      lastname:
        required: true

  User-new:
    type: User-base
    properties:
      HRAuth:
        description: The authorization received from HR
        required: true

  User-update:
    properties:
      firstname:
      lastname:

  User:
    type: [ User-base, c.Record-base ]
    properties:
      emails: c.Email[]
