#%RAML 1.0 Resource Type

###############
# Member:
###############

member:
  get:
    responses:
      200:
        body:
          type: <<typename>>
  patch:
    body:
      type: <<typename-update>>
    responses:
      200:
        body:
          type: <<typename>>
  delete:
    responses:
      204:
